### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#288]
After updating to version 0.4.2, running the tutorial code will report an error. The 0.4.1 version is OK.

```
Traceback (most recent call last):
  File "E:\pythonWorkplace\ReconstructionReg\ReconReg.py", line 21, in <module>
    gt = drr(pose)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\diffdrr\drr.py", line 131, in forward
    img = self.renderer(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\diffdrr\renderers.py", line 46, in forward
    alphas = _get_alphas(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\diffdrr\renderers.py", line 118, in _get_alphas
    alphas = _filter_intersections_outside_volume(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\diffdrr\renderers.py", line 131, in _filter_intersections_outside_volume
    alphas = alphas[..., good_idxs.any(dim=[0, 1])]
TypeError: any() received an invalid combination of arguments - got (dim=list, ), but expected one of: * () didn't match because some of the keywords were incorrect: dim * (int dim, bool keepdim)* (name dim, bool keepdim)
```

**Comment by shenao1994** [comment]
When I set the filter_intersections_outside_volume in the Siddon class to false, it works.

**Comment by eigenvivek** [comment]
This is because you need to update pytorch to version `2.2`.

In previous versions, you had to use syntax like

```python
good_idxs.any(dim=0).any(dim=0)
```

But in version `2.2`, you can simplify this to

```python
good_Idxs.any(dim=[0, 1])
```

Note that the latest version (`pytorch=2.3`) might not work because it is incompatible with `torchio` (see #283).

**Comment by shenao1994** [comment]
I got it! Thank you for your help!

**Comment by shenao1994** [comment]
> This is because you need to update pytorch to version `2.2`.
> 
> In previous versions, you had to use syntax like
> 
> ```python
> good_idxs.any(dim=0).any(dim=0)
> ```
> 
> But in version `2.2`, you can simplify this to
> 
> ```python
> good_Idxs.any(dim=[0, 1])
> ```
> 
> Note that the latest version (`pytorch=2.3`) might not work because it is incompatible with `torchio` (see #283).


I got it! Thank you for your help!
